### ISSUE TITLE
[feature] Query data

### ISSUE THREAD

**Issue by robertugo2** [jacek2511/ha_rce#1]
Hi,

Is it possible to add a service to query data? For example I would like to query, what price will be at 1pm.

Or if not, is it possible to export data as a string, where each price is delimeted? Like "xx.x, yy.y, ..."

Thanks!

**Comment by jacek2511** [comment]
Hi,

This can be done easily. Just add in configuration.yaml:
```input_datetime:
  enter_time:
    name: Enter the time
    has_date: false
    has_time: true

sensor:
  - platform: template
    sensors:
      energy_price_at:
        device_class: monetary
        value_template: >
          {% set hour = int(states('input_datetime.enter_time')[:2]) %}
          {{ state_attr('sensor.rynkowa_cena_energii_elektrycznej', 'today')[hour]['tariff'] }}
```

and then in the dashboard, e.g.

```
type: entities
entities:
   - entity: input_datetime.enter_time
   - entity: sensor.energy_price_at
```
PS. Prices for the current and next day are also included as sensor attributes
