### ISSUE TITLE
Do I have to automate the updating?

### ISSUE THREAD

**Issue by darmach** [jacek2511/ha_rce#15]
Hi @jacek2511 I'm checking out your integration and I would like to ask few questions.

I do get that we get two entitites `calendar.rce_calendar` and update.rce_calendar_update with following attributes:

```
calendar.rce_calendar:
  message: 628.97
  all_day: false
  start_time: 2024-11-27 20:00:00
  end_time: 2024-11-27 21:00:00
  location: 
  description: https://www.pse.pl/dane-systemowe/funkcjonowanie-rb/raporty-dobowe-z-funkcjonowania-rb/podstawowe-wskazniki-cenowe-i-kosztowe/rynkowa-cena-energii-elektrycznej-rce
  friendly_name: RCE calendar
  
update.rce_calendar_update:
  auto_update: false
  display_precision: 0
  installed_version: 504fddc
  in_progress: false
  latest_version: 504fddc
  release_summary: null
  release_url: https://github.com/PePeLLee/home-assistant-rce
  skipped_version: null
  title: null
  update_percentage: null
  entity_picture: https://brands.home-assistant.io/_/rce/icon.png
  friendly_name: RCE calendar update
  supported_features: 23
```
Noticing `auto_update` attribute of the latter, I started wondering - should I somehow either set it to true (would that do anything?) or set up an automation to trigger the update?

For now I just created a helper sensor with attributes:
```
unit_of_measurement: PLN/kWh
icon: mdi:currency-usd
friendly_name: rce test
```
and templated value:
```
{{ state_attr('calendar.rce_calendar', 'message') | float / 1000 }}
```
And added it into energy dashboard as `return to grid` "Use an entity with current rate" - that should be all right?
